DOCKER_COMPOSE := docker compose

.PHONY: build
build:
	${DOCKER_COMPOSE} build

.PHONY: serve
serve:
	${DOCKER_COMPOSE} up -d

.PHONY: clean
clean:
	${DOCKER_COMPOSE} down

.PHONY: logs
logs:
	${DOCKER_COMPOSE} logs
